# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Specify version or tag to use (as of 24.7.14)
    rev: v4.6.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
      # Unify line break code to LF
      - id: mixed-line-ending
        args: [--fix=lf]
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    # Cannot be executed with local designation (as of 23.10.8)
    rev: 1.8.3
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$
      - id: poetry-export
        name: poetry-export-dev
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix","ton_txns_data_conv"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20240622]
        args: [--config-file=pyproject.toml]
